name: CI-CD

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
    paths:
      - 'src/**'
      - 'k8s/**'
env:
  docker_image_name: fabricioveronez/kube-news:${{github.run_number}}
jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
    - name: Obtendo o código
      uses: actions/checkout@v3
    - name: Docker Login
      uses: docker/login-action@v3.0.0
      with:
        username: ${{secrets.DOCKERHUB_USER}}
        password: ${{secrets.DOCKERHUB_PWD}}
    - name: Construção da imagem Docker worker
      uses: docker/build-push-action@v5.0.0
      with: 
        context: ./src
        file: ./src/Dockerfile
        push: true
        tags: |
          ${{ env.docker_image_name }}
          fabricioveronez/kube-news:latest
  CD:
    runs-on: ubuntu-latest
    needs: [CI]
    
    steps:
    - name: Obtendo o código
      uses: actions/checkout@v3
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - uses: azure/k8s-set-context@v4
      with:
        method: kubeconfig
        kubeconfig: ${{ secrets.K8S_CONFIG }}
    - name: Deploy to Kubernetes cluster
      uses: Azure/k8s-deploy@v4.9
      with:
        manifests: |
          ./k8s/deployment.yaml
        images: |
          ${{ env.docker_image_name }}



          
